name: Validate

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - edited
      - synchronize

env:
  TERM: linux
  FORCE_COLOR: 1

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Restore
        run: |
          set -e
          pnpm install --frozen-lockfile
          pnpm install --global wurk

      - name: Build
        run: |
          set -e
          wurk build
          wurk publish --to-archive

      - name: Test
        run: |
          set -e
          wurk eslint -- --max-warnings=0
          wurk depcheck
          wurk vitest run

      - name: Publish (Dry Run)
        run: |
          set -e
          wurk publish --from-archive --dry-run
