name: Validate

on:
  pull_request:
    branches:
      - main

env:
  TERM: linux
  FORCE_COLOR: 1

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Restore
        run: npm ci

      - name: Build
        run: |
          set -e
          npm run build
          npx @werk/cli publish --no-build --to-archive

      - name: Test
        run: |
          set -e
          npm run lint -- --max-warnings=0
          npx @werk/cli vitest run --no-build
          npx @werk/cli depcheck

      - name: Publish (Dry Run)
        run: npx @werk/cli publish --from-archive --dry-run
